### ISSUE TITLE
dcvc训练相关请求

### ISSUE THREAD

**Issue by nanjh** [Cicecoo/DCVC-Trainer#1]
大佬你好，我看到你放上的有关dcvc训练的代码，有些问题特想请教一下。能麻烦加个vx吗？

**Comment by Cicecoo** [comment]
可以的，不过我是刚开始学习，没能复现论文的效果。方便的话可以留个邮箱之类的吗？

**Comment by nanjh** [comment]
> 可以的，不过我是刚开始学习，没能复现论文的效果。方便的话可以留个邮箱之类的吗？
1440528931@qq.com 佬方便的话加个qq
