### ISSUE TITLE
DCVC的训练问题

### ISSUE THREAD

**Issue by wang20220117** [Cicecoo/DCVC-Trainer#3]
你好作者，感谢您的训练代码，我有个问题想要请教您。
```
if self.step == 1 or self.step == 4: # or self.step == 1:
            loss_settings["R-item"].append("mv_latent_rate") # gt 
            loss_settings["R-item"].append("mv_prior_rate") # st
        if self.step == 3 or self.step == 4:
            loss_settings["R-item"].append("frame_latent_rate") # yt
            loss_settings["R-item"].append("frame_prior_rate") # zt
```
您在训练的不同阶段，率的损失中的成分都会发生变化，我在训练时发现不同epoch中psnr和bpp变化很大，比如当前epoch相比上一个epoch，psnr降低很多而bpp增大很多。
我的问题是您这样设置有什么积极意义吗？为什么不在一开始将这4个率损失都添加到loss里呢？

**Comment by Cicecoo** [comment]
你好，
代码中loss是根据论文描述设置的，即
![image](https://github.com/user-attachments/assets/517fd4c4-d355-4de2-a5da-e97ab94582bb)
参考 https://arxiv.org/abs/2109.15047v2 的附录部分

**Comment by wang20220117** [comment]
> 你好， 代码中loss是根据论文描述设置的，即 ![image](https://private-user-images.githubusercontent.com/89625845/394205817-517fd4c4-d355-4de2-a5da-e97ab94582bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4Mjg5OTUsIm5iZiI6MTczMzgyODY5NSwicGF0aCI6Ii84OTYyNTg0NS8zOTQyMDU4MTctNTE3ZmQ0YzQtZDM1NS00ZGUyLWE1ZGEtZTk3YWI5NDU4MmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDExMDQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzc2NzIxOWMxYjQyOGU2MWVhM2NiMTNmNDhiYTE1MWRkNzM2YjEwYTVlZjcwNjZkYTU0ZGRmNzAxZGNlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iiUM68dOCUX8EHzCgSbRtUwh5uMbIO8kZ5nDeybBC4Y) 参考 https://arxiv.org/abs/2109.15047v2 的附录部分

好的，谢谢回复
